In [1]:
import numpy as np

In [4]:
#Trigonometric Functions
n = np.sin(np.pi/2)

print(n)

1.0


In [6]:
a = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])

b = np.sin(a)

print(b)

[1.         0.8660254  0.70710678 0.58778525]


In [8]:
#Convert Degrees Into Radians
a1 = np.array([45 ,90 ,180,260,360])

b1 = np.deg2rad(a1)

print(b1)

[0.78539816 1.57079633 3.14159265 4.53785606 6.28318531]


In [9]:
#Radians to Degrees
a2 = np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])

b2 = np.deg2rad(a2)

print(b2)

[0.02741557 0.05483114 0.0822467  0.10966227]


In [10]:
#Finding Angles
n1 = np.arcsin(1.0)

print(n1)

1.5707963267948966


In [11]:
#Angles of Each Value in Arrays
a3 = np.array([2 ,-2 ,0.2])

b3 = np.arcsin(a3)

print(b3)

[       nan        nan 0.20135792]


C:\Users\saleh\AppData\Local\Temp\ipykernel_9768\1967501474.py:4: RuntimeWarning: invalid value encountered in arcsin
  b3 = np.arcsin(a3)


In [12]:
#Hypotenues
base = 3
prep = 4

b4 = np.hypot(base,prep)

print(b4)

5.0
