In [1]:
import numpy as np

In [4]:
#Create Sets in NumPy
a = np.array([1 ,2 ,2 ,4 ,3 ,4 ,5 ,6 ,7 ,8 ,8])

b = np.unique(a)

print(b)

[1 2 3 4 5 6 7 8]


In [6]:
#Finding Union
a1 = np.array([1 ,3 ,6 ,7 ,8])
a2 = np.array([2 ,4 ,3 ,8 ,9])

b1 = np.union1d(a1,a2)

print(b1)

[1 2 3 4 6 7 8 9]


In [8]:
#Finding Intersection
a1 = np.array([1 ,3 ,6 ,7 ,8])
a2 = np.array([2 ,4 ,3 ,8 ,9])

b2 = np.intersect1d(a1,a2, assume_unique=True)

print(b2)

[3 8]


In [11]:
#Finding Difference
a1 = np.array([1 ,3 ,6 ,7 ,8])
a2 = np.array([2 ,4 ,3 ,8 ,9])

b3 = np.setdiff1d(a1,a2,assume_unique=True)

print(b3)

[1 6 7]


In [10]:
#Finding Symmetric Difference
a1 = np.array([1 ,3 ,6 ,7 ,8])
a2 = np.array([2 ,4 ,3 ,8 ,9])

b4 = np.setxor1d(a1,a2,assume_unique=True)

print(b4)

[1 2 4 6 7 9]
