In [2]:
import numpy as np

In [3]:
#Addition
a1 = np.array([12 ,44 ,34 ,23 ,23])
a2 = np.array([42 ,76 ,98 ,32 ,88])

a3 = np.add(a1,a2)

print(a3)

[ 54 120 132  55 111]


In [7]:
#Subtraction
a1 = np.array([12 ,32 ,42 ,62])
a2 = np.array([35 ,16 ,78 ,11])

a3 = np.subtract(a1,a2)

print(a3)

[-23  16 -36  51]


In [8]:
#Multiplication
a1 = np.array([2 ,4 ,6 ,7])
a2 = np.array([5 ,6 ,2 ,1])

a3 = np.multiply(a1,a2)

print(a3)

[10 24 12  7]


In [10]:
#Division
a1 = np.array([21,55,12,15])
a2 = np.array([7 ,12 ,6 ,3])

a3 = np.divide(a1,a2)

print(a3)

[3.         4.58333333 2.         5.        ]


In [12]:
#power توان
a1 = np.array([8 ,40 ,4 ,60 ,20])
a2 = np.array([2 ,4 ,6 ,3 ,5 ])

a3 = np.power(a1,a2)

print(a3)

[     64 2560000    4096  216000 3200000]


In [13]:
#Remainder
a1 = np.array([12, 21, 35, 43, 57, 88])
a2 = np.array([3, 7, 9, 8, 2, 33])

a3 = np.mod(a1,a2)

a4 = np.remainder(a1,a2)

print(a3)
print(a4)

[ 0  0  8  3  1 22]
[ 0  0  8  3  1 22]


In [14]:
#Quotient and Mod
a1 = np.array([20,12,43,14,16])
a2 = np.array([5 ,4 ,12 ,4 ,6])

a3 = np.divmod(a1,a2)

print(a3)

(array([4, 3, 3, 3, 2]), array([0, 0, 7, 2, 4]))


In [17]:
#Absolute Values
a1 = np.array([-1,-2,1 ,4 ,-5])

a2 = np.absolute(a1)

a3 = np.abs(a1)

print(a2)
print(a3)

[1 2 1 4 5]
[1 2 1 4 5]
