In [1]:
import numpy as np

In [5]:
#Join two arrays

a1 = np.array([1 ,2 ,3 ,4])

a2 = np.array([5 ,6 ,7 ,8])

a3 = np.concatenate((a1, a2))

print(a3)

[1 2 3 4 5 6 7 8]


In [9]:
a4 = np.array([[1, 2], [3, 4]])

a5 = np.array([[5, 6], [7, 8]])

a6 = np.concatenate((a4 ,a5), axis=1)

print(a6)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
#Joining Arrays Using Stack Functions
a8 = np.array([1, 2, 3])

a7 = np.array([4, 5, 6])

a9 = np.stack((a7 ,a8),axis=1)

print(a9)

[[4 1]
 [5 2]
 [6 3]]


In [19]:
#Stacking Along Rows
a1 = np.array([1, 2, 3])

a2 = np.array([4, 5, 6])

a3 = np.hstack((a1 ,a2))

print(a3)

[1 2 3 4 5 6]


In [21]:
#Stacking Along Columns
a1 = np.array([1, 2, 3])

a2 = np.array([4, 5, 6])

a3 = np.vstack((a1 ,a2))

print(a3)

[[1 2 3]
 [4 5 6]]


In [22]:
#Stacking Along Height (depth)
a1 = np.array([1, 2, 3])

a2 = np.array([4, 5, 6])

a3 = np.dstack((a1 ,a2))

print(a3)

[[[1 4]
  [2 5]
  [3 6]]]
