In [1]:
import numpy as np

In [2]:
a1 = np.array([3, 2, 0, 1])

print(np.sort(a1))

[0 1 2 3]


In [3]:
a2 = np.array(["d","g","a","c"])

print(np.sort(a2))

['a' 'c' 'd' 'g']


In [4]:
a3 = np.array([True,True,False,True])

print(np.sort(a3))

[False  True  True  True]


In [5]:
a4 = np.array([[4,6,2],[1,5,3]])

print(np.sort(a4))

[[2 4 6]
 [1 3 5]]
