In [2]:
import numpy as np

In [5]:
#copy
a1 = np.array([1 ,2 ,3 ,4 ,5])

a2 = a1.copy()
a1[0] =80

print(a1)
print(a2)

[80  2  3  4  5]
[1 2 3 4 5]


In [7]:
#view
a3 =np.array([1 ,3 ,4 ,5])

a4 = a3.view()
a3[0]=34 

print(a3)
print(a4)

[34  3  4  5]
[34  3  4  5]


In [8]:
#Make Changes in the VIEW
a5 = np.array([1 ,2 ,3 ,4 ,5])

a6 = a5.view()
a6[0]=55

print(a5)
print(a6)

[55  2  3  4  5]
[55  2  3  4  5]


In [9]:
#Check if Array Owns its Data
a7 = np.array([1 ,2 ,3 ,4 ,5])

a8 = a7.copy()
a9 = a7.view()

print(a8.base)
print(a9.base)

None
[1 2 3 4 5]
