In [1]:
import numpy as np

In [5]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

a2 = a1.reshape(4,3)

print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

a4 = a3.reshape(2 ,3 ,2)

print(a4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
#Check if the returned array is a copy or a view:
a5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(a5.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [11]:
#returns the original array, so it is a view.

In [13]:
#Unknown Dimension
a6 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a7 = a6.reshape(2 ,2 ,-1)

print(a7)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#Flattening the arrays
a8 = np.array([[1, 2, 3], [4, 5, 6]])

a9 = a8.reshape(-1)

print(a9)

[1 2 3 4 5 6]
